params:
- config: configuration for the cli
  default:
    namespace: fabric-dev
    user: Admin
    peer: peer0
    org: org1
    peer_service_name: peer0-org1
    admin_service_name: admin-org1
    client_service_name: admin-peer0-org1-cli
deployment:
  namespace: ${config.namespace}
  name: ${config.client_service_name}
  replicas: 1
  selector:
    app: ${config.client_service_name}
  containers:
  - name: cli
    image: hyperledger/fabric-tools:x86_64-1.0.5
    env:
    - GOPATH=/opt/gopath
    - CORE_VM_ENDPOINT=http://localhost:2375
    - CORE_PEER_ID=cli
    - CORE_PEER_ADDRESS=${config.peer_service_name}:7051
    - CORE_PEER_LOCALMSPID=Org1MSP
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    - CORE_CHAINCODE_KEEPALIVE=10
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_TLS_ENABLED=false
    wd: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command:
    - sleep
    - infinity
    expose:
    - 7051
    - 7053
    volume:
    - mount: /etc/hyperledger/fabric
      store: files-target
  - name: dind
    image: docker:dind
    privileged: true
    volume:
    - mount: /var/lib/docker
      store: docker-graph-storage
  init_containers:
  - name: tar
    image: ubuntu:16.04
    command:
    - sh
    - -c
    - |
      set -e
      set -x
      cd /target
      cp -Lr /config-source/* .
      tar -xvf /msp-source/msp.tar.gz
    volume:
    - mount: /target
      store: files-target
    - mount: /config-source
      store: config
    - mount: /msp-source
      store: msp-config
  termination_grace_period: 10
  restart_policy: always
  volumes:
    docker-graph-storage: empty_dir
    files-target: empty_dir
    msp-config:
      items:
        msp.tar.gz: bundle
      vol_id: ${config.admin_service_name}-msp
      vol_type: secret
    config:
      items:
        core.yaml: file
      vol_id: core-yaml
      vol_type: config-map
