apiVersion: v1
kind: Service
metadata:
  name: orderer
  namespace: hltest
spec:
  ports:
  - name: "7050"
    port: 7050
    protocol: TCP
  selector:
    app: orderer-example-com
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orderer-example-com
  namespace: hltest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderer-example-com
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: orderer-example-com
    spec:
      containers:
      - command:
        - orderer
        env:
        - name: ORDERER_GENERAL_LOGLEVEL
          value: debug
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_GENERAL_GENESISFILE
          value: /var/hyperledger/orderer/genesis/orderer.genesis.block
        - name: ORDERER_GENERAL_LOCALMSPID
          value: OrdererMSP
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /var/hyperledger/orderer/msp
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "false"
        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: /var/hyperledger/orderer/tls/server.key
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: /var/hyperledger/orderer/tls/server.crt
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: '[/var/hyperledger/orderer/tls/ca.crt]'
        image: hyperledger/fabric-orderer:x86_64-1.1.0-alpha
        name: orderer
        ports:
        - containerPort: 7050
          protocol: TCP
        volumeMounts:
        - mountPath: /var/hyperledger/orderer
          mountPropagation: ""
          name: files
        - mountPath: /var/hyperledger/orderer/genesis
          mountPropagation: ""
          name: genesis
        - mountPath: /etc/hyperledger/fabric
          mountPropagation: ""
          name: config
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric
      initContainers:
      - command:
        - sh
        - -c
        - |
          set -e
          set -x
          cd /target
          tar -xvf /msp-source/msp.tar.gz
          tar -xvf /tls-source/tls.tar.gz
        image: ubuntu:16.04
        name: tar
        volumeMounts:
        - mountPath: /target
          mountPropagation: ""
          name: files
        - mountPath: /msp-source
          mountPropagation: ""
          name: msp-config
        - mountPath: /tls-source
          mountPropagation: ""
          name: tls-config
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      volumes:
      - name: config
        projected:
          sources:
          - configMap:
              items:
              - key: file
                path: core.yaml
              name: core-yaml
          - configMap:
              items:
              - key: file
                path: orderer.yaml
              name: orderer-yaml
      - emptyDir: {}
        name: files
      - name: genesis
        secret:
          items:
          - key: file
            path: orderer.genesis.block
          secretName: orderer-genesis-block
      - name: msp-config
        secret:
          items:
          - key: bundle
            path: msp.tar.gz
          secretName: orderer-example-com-msp
      - name: tls-config
        secret:
          items:
          - key: bundle
            path: tls.tar.gz
          secretName: orderer-example-com-tls

